name: Build image

on:
  # schedule:
  #   # every Sunday (so it's stable through the week)
  #   - cron: '0 0 * * SUN'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: log in to docker
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: jaredreisinger
        DOCKER_PASSWORD: ${{ secrets.docker_password }}

    - name: examine directory
      run: |
        pwd
        ls -laF
        ls -laF ../
        ls -laF ../../

    - name: build image
      uses: actions/docker/cli@master
      with:
        args: build --tag jaredreisinger/semantic-release:latest .

    - name: push image
      uses: actions/docker/cli@master
      with:
        args: push jaredreisinger/semantic-release:latest
