name: Build and publish image

on:
  schedule:
    # every Sunday (so it's stable through the week)
    - cron: '0 0 * * SUN'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # The actions/docker repository has disappeared, but we should be able to use the
      # docker command available directly in the virtual environment.
      - name: build and publish
        run: |
          docker login --username jaredreisinger --password ${{ secrets.docker_access_token }}
          docker build --tag jaredreisinger/semantic-release:latest .
          docker push jaredreisinger/semantic-release:latest
          
