name: Build and publish image

on:
  schedule:
    # every Sunday (so it's stable through the week)
    - cron: '0 0 * * SUN'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/docker/cli@master
        with:
          args: build --tag jaredreisinger/semantic-release:latest .

      - uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: jaredreisinger
          DOCKER_PASSWORD: ${{ secrets.docker_password }}

      - uses: actions/docker/cli@master
        with:
          args: push jaredreisinger/semantic-release:latest
