name: Build image (weekly or push)

on:
  # if we ever update things...
  push:
    branches:
      - master
  # and/or every Sunday (so it's stable through the week)
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: log in to docker
      uses: actions/docker/login@master
      secrets:
        - DOCKER_USERNAME
        - DOCKER_PASSWORD

    - name: build image
      uses: actions/docker/cli@master
      args: build --tag jaredreisinger/semantic-release:latest .

    - name: push image
      uses: actions/docker/cli@master
      args: push jaredreisinger/semantic-release:latest
